import streamlit as st
import json
from utils.data_loader import MockDataLoader
from utils.email_processor import EmailProcessor

def main():
    st.title("📝 Draft Composer")
    st.markdown("Create and manage email drafts generated by your AI assistant")
    
    # Initialize services
    if 'email_processor' not in st.session_state:
        st.session_state.email_processor = EmailProcessor()
    if 'data_loader' not in st.session_state:
        st.session_state.data_loader = MockDataLoader()
    if 'saved_drafts' not in st.session_state:
        st.session_state.saved_drafts = []
    
    # Check if emails are loaded
    emails_loaded = st.session_state.get('emails_loaded', False)
    emails = st.session_state.get('emails', [])
    
    # Main interface
    col1, col2 = st.columns([1, 1])
    
    with col1:
        st.subheader("✍️ Create New Draft")
        
        # Draft type selection
        draft_type = st.radio(
            "Draft Type:",
            ["Reply to Email", "New Email", "Follow-up"]
        )
        
        if draft_type == "Reply to Email" and emails_loaded:
            # Email selection for replies
            email_options = {f"{e['id']}: {e['subject']}": e for e in emails}
            selected_email_label = st.selectbox(
                "Select email to reply to:",
                options=list(email_options.keys()),
                index=0
            )
            selected_email = email_options[selected_email_label]
            
            # Show original email context
            with st.expander("📧 Original Email"):
                st.write(f"**From:** {selected_email['sender']}")
                st.write(f"**Subject:** {selected_email['subject']}")
                st.write(f"**Body:** {selected_email['body']}")
            
            # Draft options
            tone = st.selectbox("Tone:", ["Professional", "Friendly", "Formal", "Casual"])
            length = st.select_slider("Length:", ["Brief", "Medium", "Detailed"])
            
            if st.button("🪄 Generate Draft Reply", type="primary"):
                with st.spinner("Generating draft..."):
                    draft = st.session_state.email_processor.draft_reply(selected_email)
                    st.session_state.current_draft = {
                        "type": "reply",
                        "to": selected_email['sender'],
                        "subject": f"Re: {selected_email['subject']}",
                        "body": draft,
                        "original_email": selected_email['id']
                    }
                    st.rerun()
        
        elif draft_type == "New Email":
            # New email composition
            to_email = st.text_input("To:", placeholder="recipient@example.com")
            subject = st.text_input("Subject:", placeholder="Email subject...")
            context = st.text_area("Context/Key Points:", placeholder="What should this email be about?")
            
            tone = st.selectbox("Tone:", ["Professional", "Friendly", "Formal", "Casual"])
            purpose = st.selectbox("Purpose:", ["General", "Meeting Request", "Project Update", "Question", "Follow-up"])
            
            if st.button("🪄 Generate New Email", type="primary"):
                if context:
                    with st.spinner("Generating draft..."):
                        # Use the AI to generate a new email
                        prompt = f"Write a {tone.lower()} email about: {context}. Purpose: {purpose}"
                        draft_body = st.session_state.email_processor.llm_service.generate_response(prompt)
                        
                        st.session_state.current_draft = {
                            "type": "new",
                            "to": to_email,
                            "subject": subject or f"{purpose} - {context[:50]}...",
                            "body": draft_body,
                            "context": context
                        }
                        st.rerun()
                else:
                    st.warning("Please provide some context for the email")
        
        elif draft_type == "Follow-up" and emails_loaded:
            # Follow-up email
            email_options = {f"{e['id']}: {e['subject']}": e for e in emails if e.get('category') in ['Important', 'To-Do']}
            if email_options:
                selected_email_label = st.selectbox(
                    "Select email to follow up on:",
                    options=list(email_options.keys())
                )
                selected_email = email_options[selected_email_label]
                
                days_ago = st.slider("Follow up after (days):", 1, 30, 7)
                purpose = st.selectbox("Follow-up purpose:", ["Check status", "Request update", "Additional information", "Reminder"])
                
                if st.button("🪄 Generate Follow-up", type="primary"):
                    with st.spinner("Generating follow-up draft..."):
                        prompt = f"Write a professional follow-up email about: {selected_email['subject']}. Purpose: {purpose}. Original context: {selected_email['body'][:200]}"
                        draft_body = st.session_state.email_processor.llm_service.generate_response(prompt)
                        
                        st.session_state.current_draft = {
                            "type": "followup",
                            "to": selected_email['sender'],
                            "subject": f"Follow-up: {selected_email['subject']}",
                            "body": draft_body,
                            "original_email": selected_email['id']
                        }
                        st.rerun()
            else:
                st.info("No suitable emails found for follow-up. Try loading emails first.")
    
    with col2:
        st.subheader("📄 Draft Preview")
        
        if 'current_draft' in st.session_state:
            draft = st.session_state.current_draft
            
            st.write("**To:**", draft.get('to', 'Not specified'))
            st.write("**Subject:**", draft.get('subject', 'No subject'))
            st.write("**Type:**", draft.get('type', 'unknown').title())
            
            st.markdown("---")
            st.write("**Draft Body:**")
            edited_draft = st.text_area(
                "Edit your draft:",
                value=draft.get('body', ''),
                height=300,
                key="draft_editor"
            )
            
            # Save draft
            col_save, col_discard = st.columns(2)
            with col_save:
                if st.button("💾 Save Draft", use_container_width=True):
                    saved_draft = draft.copy()
                    saved_draft['body'] = edited_draft
                    st.session_state.saved_drafts.append(saved_draft)
                    st.success("Draft saved!")
                    del st.session_state.current_draft
                    st.rerun()
            
            with col_discard:
                if st.button("🗑️ Discard", use_container_width=True):
                    del st.session_state.current_draft
                    st.rerun()
        else:
            st.info("👆 Generate a draft to see it here")
        
        st.markdown("---")
        st.subheader("📂 Saved Drafts")
        
        if st.session_state.saved_drafts:
            for i, draft in enumerate(st.session_state.saved_drafts):
                with st.expander(f"📝 {draft.get('subject', 'Draft')}"):
                    st.write(f"**To:** {draft.get('to', 'Not specified')}")
                    st.write(f"**Type:** {draft.get('type', 'unknown').title()}")
                    st.write("**Body:**")
                    st.write(draft.get('body', 'No content'))
                    
                    col_edit, col_delete = st.columns(2)
                    with col_edit:
                        if st.button("✏️ Edit", key=f"edit_{i}"):
                            st.session_state.current_draft = draft
                            st.session_state.saved_drafts.pop(i)
                            st.rerun()
                    with col_delete:
                        if st.button("🗑️ Delete", key=f"delete_{i}"):
                            st.session_state.saved_drafts.pop(i)
                            st.rerun()
        else:
            st.info("No saved drafts yet")

# Helper function to generate email from template
def generate_email_template(draft_type: str, context: dict) -> str:
    """Generate email template based on type and context"""
    templates = {
        "reply": """Thank you for your email regarding {topic}.

I've reviewed your message and {response}.

Best regards,
[Your Name]""",
        
        "meeting": """Hi {name},

I'd like to schedule a meeting to discuss {topic}. 

Would you be available sometime {timeframe}?

Looking forward to connecting.

Best,
[Your Name]""",
        
        "followup": """Hi {name},

Just following up on our previous conversation about {topic}.

{request}

Thanks,
[Your Name]"""
    }
    
    return templates.get(draft_type, "Email content goes here.")

if __name__ == "__main__":
    main()